In [4]:
#assignment 4
import numpy as ny
x=ny.array([[1,2,3],[4,5,6]])
y=ny.array([[7,8,9],[10,11,12]])
print(x)
print(y)
print(x+y)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
